<!DOCTYPE html>
<html>
	<h2> Delete a Meeting </h2>
	<form action="Conferences/Repository/MeetingRepository" method="GET">
		<table>

			<tr><p>Enter the id of the meeting which you want to delete : </p>
				<input type="text" name="id" size="40" placeholder="id">						
			</tr><br><br>

			<input type ="submit" value="Delete">
			<input type ="reset" value="Annuler">
	</form>
</html> 